version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - aws --version
      
  build:
    commands:
      - echo "Starting build phase..."
      
  post_build:
    commands:
      - echo "Starting post-build phase..."
      - ls -la
      # - aws s3 cp ./path/to/your/files/ s3://your-bucket-name/target-path/ --recursive
      - echo "Upload completed"

artifacts:
  files:
    - '**/*'
  base-directory: 'path/to/your/files'
