AWSTemplateFormatVersion: '2010-09-09'
Description: 'Gyazo-like service using AWS services with Basic Authentication and CloudFront'

Parameters:
  ImageBucketName:
    Type: String
    Description: Name of the S3 bucket to store images
  BasicAuthUsername:
    Type: String
    Description: Username for Basic Authentication
  BasicAuthPassword:
    Type: String
    Description: Password for Basic Authentication
    NoEcho: true
  ViewerBucketName:
    Type: String
    Description: Name of the S3 bucket to locate viewer site
  ImagesJsonFilenamePath:
    Type: String
    Default: viewer/images.json
    Description: This Json file logs filenames stored in ImageBucket

Resources:
  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ImageBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  CloudFrontOriginAccessIdentityForImageBucket:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "OAI for ${ImageBucketName}"

  CloudFrontOriginAccessIdentityForViewerBucket:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "OAI for ${ViewerBucketName}"

  ImageBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ImageBucket
      PolicyDocument:
        Statement:
          - Action: 's3:GetObject'
            Effect: Allow
            Resource: !Sub '${ImageBucket.Arn}/*'
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentityForImageBucket.S3CanonicalUserId

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          ForwardedValues:
            QueryString: false
          TargetOriginId: ImageS3Origin
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        HttpVersion: http2
        Origins:
          - DomainName: !GetAtt ImageBucket.RegionalDomainName
            Id: ImageS3Origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentityForImageBucket}'
          - DomainName: !GetAtt ViewerBucket.RegionalDomainName
            Id: ViewerS3Origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentityForViewerBucket}'
        PriceClass: PriceClass_100
        CacheBehaviors:
          - PathPattern: '/viewer/*'
            TargetOriginId: ViewerS3Origin
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            ForwardedValues:
              QueryString: false
            ViewerProtocolPolicy: redirect-to-https

  UploadLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: !Sub ${ImageBucket.Arn}/*

  UploadFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt UploadLambdaExecutionRole.Arn
      Code:
        ZipFile: |
          const { S3Client, PutObjectCommand } = require('@aws-sdk/client-s3');
          const s3Client = new S3Client({ region: process.env.AWS_DEFAULT_REGION });

          exports.handler = async (event) => {
            try {
              const body = JSON.parse(event.body);
              const imageData = Buffer.from(body.image, 'base64');
              const key = `${Date.now()}.png`;

              const command = new PutObjectCommand({
                Bucket: process.env.BUCKET_NAME,
                Key: key,
                Body: imageData,
                ContentType: 'image/png',
                StorageClass: 'GLACIER_IR'  // ?????????Glacier Instant Retrieval???
              });

              await s3Client.send(command);

              return {
                statusCode: 200,
                headers: {
                  'Content-Type': 'application/json'
                },
                body: JSON.stringify({
                  url: `https://${process.env.CLOUDFRONT_DOMAIN}/${key}`
                })
              };
            } catch (error) {
              console.error('Error:', error);
              return {
                statusCode: 500,
                headers: {
                  'Content-Type': 'application/json'
                },
                body: JSON.stringify({ error: 'An error occurred while processing your request.' })
              };
            }
          };
      Runtime: nodejs22.x
      Timeout: 10
      Environment:
        Variables:
          BUCKET_NAME: !Ref ImageBucket
          CLOUDFRONT_DOMAIN: !GetAtt CloudFrontDistribution.DomainName

  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: ImageUploadAPI

  ApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: upload
      RestApiId: !Ref ApiGateway

  ApiAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: BasicAuthorizer
      Type: REQUEST
      IdentitySource: method.request.header.Authorization
      RestApiId: !Ref ApiGateway
      AuthorizerUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AuthorizerFunction.Arn}/invocations
      AuthorizerResultTtlInSeconds: 300

  ApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: POST
      ResourceId: !Ref ApiResource
      RestApiId: !Ref ApiGateway
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref ApiAuthorizer
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UploadFunction.Arn}/invocations


  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: ApiMethod
    Properties:
      RestApiId: !Ref ApiGateway
      StageName: prod

  LambdaApiGatewayPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt UploadFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*/POST/upload

  AuthorizerFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt UploadLambdaExecutionRole.Arn
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            const authHeader = event.headers.Authorization || event.headers.authorization;
            if (!authHeader) return generatePolicy('user', 'Deny', event.methodArn);
            
            const encodedCreds = authHeader.split(' ')[1];
            const plainCreds = Buffer.from(encodedCreds, 'base64').toString().split(':');
            const username = plainCreds[0];
            const password = plainCreds[1];
            
            if (username === process.env.AUTH_USERNAME && password === process.env.AUTH_PASSWORD) {
              return generatePolicy('user', 'Allow', event.methodArn);
            }
            
            return generatePolicy('user', 'Deny', event.methodArn);
          };

          const generatePolicy = (principalId, effect, resource) => {
            return {
              principalId: principalId,
              policyDocument: {
                Version: '2012-10-17',
                Statement: [{
                  Action: 'execute-api:Invoke',
                  Effect: effect,
                  Resource: resource
                }]
              }
            };
          };
      Runtime: nodejs22.x
      Environment:
        Variables:
          AUTH_USERNAME: !Ref BasicAuthUsername
          AUTH_PASSWORD: !Ref BasicAuthPassword

  AuthorizerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref AuthorizerFunction
      Principal: apigateway.amazonaws.com

# -----------------------------------------------------------------------------------------------
# 画像閲覧サイトホスティング用 S3 バケット
# -----------------------------------------------------------------------------------------------

  ViewerBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ViewerBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - "*"
            AllowedMethods:
              - GET
            AllowedHeaders:
              - "*"
            MaxAge: 3000

  ViewerBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ViewerBucket
      PolicyDocument:
        Statement:
          - Action: 's3:GetObject'
            Effect: Allow
            Resource: !Sub '${ViewerBucket.Arn}/*'
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentityForViewerBucket.S3CanonicalUserId

# -----------------------------------------------------------------------------------------------
# images.json 更新用リソース
# -----------------------------------------------------------------------------------------------

  # UpdateImagesJsonLambda 用IAMロール
  UpdateImagesJsonLambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'lambda.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'S3AccessPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 's3:ListBucket'
                  - 's3:GetObject'
                  - 's3:PutObject'
                Resource:
                  - !Sub 'arn:aws:s3:::${ViewerBucket}'
                  - !Sub 'arn:aws:s3:::${ViewerBucket}/*'
                  - !Sub 'arn:aws:s3:::${ImageBucket}'
                  - !Sub 'arn:aws:s3:::${ImageBucket}/*'
              - Effect: 'Allow'
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:*'

  UpdateImagesJsonLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: 'UpdateImagesJsonFunction'
      Handler: 'index.handler'
      Role: !GetAtt UpdateImagesJsonLambdaExecutionRole.Arn
      Code:
        ZipFile: |
          const { S3Client, ListObjectsV2Command, PutObjectCommand } = require('@aws-sdk/client-s3');

          const s3Client = new S3Client({ region: process.env.AWS_DEFAULT_REGION });

          exports.handler = async (event) => {
            const imageBucket = process.env.IMAGE_BUCKET;
            const viewerBucket = process.env.VIEWER_BUCKET;
            const fileName = process.env.IMAGES_JSON_FILENAME_PATH;

            try {
              // viewerBucket内のオブジェクトリストを取得
              const listObjectsCommand = new ListObjectsV2Command({ Bucket: imageBucket });
              const listObjectsResponse = await s3Client.send(listObjectsCommand);
              const fileNames = listObjectsResponse.Contents.map(object => object.Key);
              console.log(fileNames);

              // images.jsonファイルとして保存するデータ作成
              const jsonData = JSON.stringify(fileNames, null, 2);
              console.log(jsonData);

              // viewerBucketにimages.jsonを保存
              const putObjectCommand = new PutObjectCommand({
                Bucket: viewerBucket,
                Key: fileName,
                Body: jsonData,
                ContentType: 'application/json',
              });

              await s3Client.send(putObjectCommand);

              return {
                statusCode: 200,
                body: 'images.json saved successfully!',
              };
            } catch (error) {
              console.error('Error processing S3 event', error);
              return {
                statusCode: 500,
                body: 'Error processing S3 event',
              };
            }
          };
      Environment:
        Variables:
          IMAGE_BUCKET: !Ref ImageBucket
          VIEWER_BUCKET: !Ref ViewerBucket
          IMAGES_JSON_FILENAME_PATH: !Ref ImagesJsonFilenamePath
      Runtime: 'nodejs22.x'  # 例としてNode.jsを使用
      Timeout: 300  # タイムアウト（300秒）

  # S3イベント通知でLambdaをトリガー
  # ImageBucketEvent:
  #   Type: 'AWS::S3::BucketNotification'
  #   Properties:
  #     Bucket: !Ref ImageBucket
  #     NotificationConfiguration:
  #       LambdaFunctionConfigurations:
  #         - Event: 's3:ObjectCreated:*'
  #           Function: !GetAtt UpdateImagesJsonLambda.Arn
          
  # Lambda関数にImageBucketへのアクセス許可を付与
  # LambdaInvokePermission:
  #   Type: 'AWS::Lambda::Permission'
  #   Properties:
  #     Action: 'lambda:InvokeFunction'
  #     FunctionName: !Ref UpdateImagesJsonLambda
  #     Principal: 's3.amazonaws.com'
  #     SourceArn: !GetAtt ImageBucket.Arn

# -----------------------------------------------------------------------------------------------

Outputs:
  ApiEndpoint:
    Description: "API Endpoint"
    Value: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/upload
  CloudFrontDomain:
    Description: "CloudFront Distribution Domain"
    Value: !GetAtt CloudFrontDistribution.DomainName
